### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by buybackoff** [Spreads/Spreads.Native#1]
MacOS x64 is probably the only thing remaining TBD here for 1.0. Will do when the entire stack is ready.

**Comment by aliostad** [comment]
Sure, can wait for now. My work still ongoing.

Cheers

**Comment by buybackoff** [comment]
LMDB works, this library fails in CI.

Pushed LMDB package. @aliostad if you do not use native compression from this lib then you could use it already.

**Comment by buybackoff** [comment]
Done

**Comment by aliostad** [comment]
It is already working, thanks!
