### ISSUE TITLE
`Vec<T>` design

### ISSUE THREAD

**Issue by buybackoff** [Spreads/Spreads.Native#3]
Original version was "unsafe" unsafe. But we do not need `ref T` from indexer for the hottest path, just simple get/set. For that unsafe is probably safe enough on the stack and returned `T` value is safe to use. 

If this is not the case then we just have the unchecked method and could use it as a field. The check `if (_pinnable == null)` is inevitable at some point without JIT native support if we need both native/managed memory. But saving on BC compensates this cost and we should be at least on par with `T[]` when used e.g. from SortedMap. Benefits on non-generic `Vec` remain.

Code is based on Span.Portable as of last commit it was in corefx https://github.com/dotnet/corefx/tree/64c6d9fe5409be14bdc3609d73ffb3fea1f35797

Add methods:

```
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public T GetUnchecked(int index)
        {
            if (typeof(T) == typeof(int))
            {
                return UnsafeEx.GetAtIndex<T>(_pinnable, _byteOffset, index);
            }

            // Other known types

            return GetRefUnchecked(index);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ref T GetRefUnchecked(int index)
        {
            if (_pinnable == null)
            {
                unsafe { return ref Unsafe.Add<T>(ref Unsafe.AsRef<T>(_byteOffset.ToPointer()), index); }
            }
            else
            {
                return ref Unsafe.Add<T>(ref Unsafe.AddByteOffset<T>(ref _pinnable.Data, _byteOffset), index);
            }
        }
```

`GetRefUnchecked` if original Span.Portable code without bound checks.

`UnsafeEx.GetAtIndex<T>` IL is:

```
	.method hidebysig static !!T GetAtIndex<T>(
		object obj, native int offset, int32 index) cil managed aggressiveinlining
	{
		.maxstack 3
        .locals([0] uint8 & addr)
        ldarg.0     // load the object
        stloc.0     // convert the object pointer to a byref
        ldloc.0     // load the object pointer as a byref
        ldarg.1     // load the offset
        add         // add the offset
        ldarg.2     // load the index
        sizeof !!T  // load size of T
        conv.i
        mul         // multiply the index and size of T
        add         // add the result
        ldobj !!T   // load a T value from the computed address
        ret
	}
```
To review:
* Maybe this `typeof(T) == typeof(int)` is not a big deal, but it's free for most important types e.g. double
* Doing binary search by first converting to Span may be faster, or we could just use the code from there directly.
* For blittables the fast path should be safe, did so many times and this was even confirmed by JK, but is this `non-ref` return from simple getter is still unsafe for types with references? I don't understand the detail: if the dereferencing itself is unsafe e.g. because GC could move the object or using the object after the method returns is unsafe. The first version of `Vec<T>` already used simple `non-ref` return. Is this `ldobj !!T` operation does not notify GC that we are using the object and that is why the reference is invalid and won't be updated when the object moves?

WIP & TBD

**Comment by omariom** [comment]
What asserts RyuJit generates for the hack?

**Comment by omariom** [comment]
I think this will generate a bit better code:
```C#
ref T baseRef = ref _pinnable == null ? 
                       ref Unsafe.AsRef<T>(_byteOffset.ToPointer() :
                       ref Unsafe.AddByteOffset<T>(ref _pinnable.Data, _byteOffset);

  return ref Unsafe.Add<T>(ref baseRef, index);
```

**Comment by buybackoff** [comment]
> What asserts RyuJit generates for the hack?

@omariom  Where do I get tutorial/info on how to check the asserts?

**Comment by buybackoff** [comment]
> I think this will generate a bit better code:

This is slower (1380 -> 1315 MOPS) likely due to local var

**Comment by buybackoff** [comment]
The problem with fast path `if (typeof(T) == typeof(int))` approach is that the two paths use different offset:

* FastPath needs first element offset: object header + array header
* Normal path for refs needs only array header adjustment: `T[0] - _pinnable.Data`

If I cache the difference in `static readonly generic` field then performance drops below the `ref` path.

@omariom it it safe to assume that object header is always 8 bytes?

**Comment by buybackoff** [comment]
Have just pushed the new implementation with a [fast path](https://github.com/Spreads/Spreads.Native/blob/73b066c710b91d20798fcdb9d8f2fa261301e0c9/dotnet/src/Spreads.Native/Vec.cs#L220-L223) for `int`. 


If [this IL](https://github.com/Spreads/Spreads.Native/blob/73b066c710b91d20798fcdb9d8f2fa261301e0c9/dotnet/src/Spreads.Native/UnsafeEx.il#L363-L383) is valid inside a calling method (no ref returned) for blittable types:

```
  .method public hidebysig static !!T DangerousGetAtIndex<T>(object obj, native int offset, int32 index) cil managed aggressiveinlining
  {
    .custom instance void System.Runtime.Versioning.NonVersionableAttribute::.ctor() = ( 01 00 00 00 )
    .maxstack 3
    .locals([0] uint8 & addr)
    ldarg.0     // load the object
    stloc.0     // convert the object pointer to a byref
    ldloc.0     // load the object pointer as a byref
    ldarg.1     // load the offset
    add         // add the offset
    ldarg.2     // load the index
    sizeof !!T  // load size of T
    conv.i
    mul         // multiply the index and size of T
    add         // add the result
    sizeof native int
    add
    unaligned. 0x1
    ldobj !!T   // load a T value from the computed address
    ret
  }
```
then fast path is possible for known types.

This modification is required to the original unsafe version to adjusts Span-like offset to Slice-like offset:

```
    sizeof native int
    add
```


## Justification

From @kkokosa post http://tooslowexception.com/managed-pointers-in-net/:

> An object reference is, in fact, a type-safe pointer (address) that always points to an object MethodTable reference field (it is often said it points at the beginning of an object). Thus, using them may be quite efficient. Having an object reference, we simply have the whole object address. For example, the GC can quickly access its header via constant offset. Addresses of fields are also easily computable due to information stored in MethodTable.

[Another post](https://blogs.msdn.microsoft.com/seteplia/2017/09/12/managed-object-internals-part-3-the-layout-of-a-managed-array-3/) on arrays explains that there is an array length after MT. 

Vec `_byteOffset` has adjustment from `Pinnable<T>.Data to T[0]`. Fast path needs offset from `T[] object reference to T[0]`.

Pinnable:
`___OH___ |* __MT__ |^ __Data__..... |`
Array:
`___OH___ |* __MT__ |^__LEN__|~__T[0]__ .....|`

Span adjustment: ` SA = |~__T[0]__| - |^__Data__| == |~__T[0]__| - |^__LEN__|`
Fast path offset: `FPO = |~__T[0]__| - |^ __MT__ |`

We need to add `MT` size to `SA` to get `FPO` and it is always a size of native int.

Fast path adjustment: `FPO = SA + sizeof<MT pointer> = SA + sizeof<native int>`

When doing this adjustment in IL performance is not affected. `int[]` fast path is 1760 MOPS vs array 1560 MOPS.

**Comment by buybackoff** [comment]
@jkotas is Slice-like unsafe approach is OK for blittable values if we return values themselves and not references to them in the getter?

(excuse me for pinging you again, but you are the definitive source of truth on this)

**Comment by jkotas** [comment]
The [spec](http://www.ecma-international.org/publications/standards/Ecma-335.htm) does not make a difference between blittable and non-blittable here. 

If you are asking whether it will happen to work on given runtime, I would recommend testing with debug builds of RyuJIT. If you see no asserts coming from RyuJIT, you are probably ok.

**Comment by buybackoff** [comment]
Another take: using sentinel object instead of null, `ldind.ref` to get valid object reference and then multiply it by one/zero depending on null status.

As far as I understood the problem was in getting reference from object passed normally. Here we pass object `byref`.

```
  .method public hidebysig static !!T& GetRef<T>(object& obj, native int offset, int32 index, int32 runtimeTypeId) cil managed aggressiveinlining
  {
    .custom instance void System.Runtime.Versioning.NonVersionableAttribute::.ctor() = ( 01 00 00 00 )
    .maxstack 3
    .locals([0] uint8 & addr)
    ldarg.0     // load the object byref reference
    ldind.ref	// load actual object reference
    stloc.0     // convert the object pointer to a byref
    ldloc.0     // load the object pointer as a byref
    ldarg.3     // load runtimeTypeId
    ldc.i4.0    // load zero int32
    cgt         // rttid is > 0 only when array is not null
    mul         // multiply by 1 if array is not null or by 0 otherwise (actuall _pinnable filed is sentinel so that ldind.ref does not throw)
    ldarg.1     // load the offset
    add         // add the offset
    ldarg.2     // load the index
    sizeof !!T  // load size of T
    conv.i      // convert size to native int
    mul         // multiply the index and size of T
    add         // add the result
    ret
  }
```

**Comment by buybackoff** [comment]
Solution with `ldarg.0 + ldind.i` works for simple getter and **no assertions failures in RyuJIT today's Debug build.** (Original version above did fail).

Current getter code:
```
IL:
  .method public hidebysig static !!T Get<T>(object& obj, 
    native int byteOffset, int32 index) cil managed aggressiveinlining
  {
    .custom instance void System.Runtime.Versioning.NonVersionableAttribute::.ctor() = ( 01 00 00 00 )
    .maxstack 3
    ldarg.0     // load the object byref reference
    ldind.i	    // load actual object reference as native int

    ldarg.1     // load the offset
    add         // add the offset
    ldarg.2     // load int32 index
    sizeof !!T  // load size of T as unsigned int32
    conv.i      // convert size to native int
    mul         // multiply the index and size of T
    add         // add the result
	
    unaligned. 0x1 // it's safer for native mem, perf is OK
    ldobj !!T   // load a T value from the computed address
    ret
  }

C#:
/// <summary>
/// Fetches the element at the specified index without bound checks.
/// </summary>
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public T GetUnchecked(int index)
{
    object p = _pinnable;
    return UnsafeEx.Get<T>(ref p, _byteOffset, index);
}
```


Interestingly, there was a commit to optimize `Span<T>` getter: https://github.com/dotnet/coreclr/pull/20386/

In the initial commit @GrabYourPitchforks wrote:

> // Ideally this method would be replaced by the VM with:
> // ldarg.0
> // ldind.i
> // ret 

Then the [following discussion happened](https://github.com/dotnet/coreclr/pull/20386/#pullrequestreview-168434985) between OP, @jkotas & @CarolEidt. As far as I understand this reference is (possibly) not tracked by GC and returning `byref` is not save. 

@jkotas 
> I do not think we would ever want this. This would mean hacking the JIT to allow derefencing objectrefs as pointers. It is invalid IL and it should stay as invalid IL.
...

Then in [PR thread](https://github.com/dotnet/coreclr/pull/20386/#issuecomment-433174793)

@AndyAyersMS
> Since you are modelling the resulting object pointer as an IntPtr there is a potential window of vulnerability where the object might move between the time you subtract to create the object pointer and the time you read from the pointer. An actual object reference will get updated but your IntPtr version won't be.

@jkotas 
> Tracked byref that points at offset 0 in the object does not show up anywhere else in the system today.

@GrabYourPitchforks
> FYI I spoke with Maoni about this offline and she indicated that having an interior pointer to the "zero" offset of an object is valid as far as GC reporting / tracking is concerned. We might still need to stress test this since as Jan suggested it's probably not a well exercised condition.


In our `Vec<T>` getter case we have a simple method that returns just `T` and not `ref T`. But does this `ldind.i` breaks tracking inside this method so that during subsequent offset addition we could add calculated offset to a stale place from where the object was moved by GC? 

Does lack of assertion failures mean this IL is OK or a missing assertion since quoting @jkotas "It is invalid IL and it should stay as invalid IL."?

**Comment by jkotas** [comment]
> `ldind.i` breaks tracking inside this method so that during subsequent offset addition we could add calculated offset to a stale place from where the object was moved by GC?

Correct.
